[package]
name = "rust-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
typify = "0.5.0"
schemars = "0.8.22"
serde_json = "1.0.145"
syn = "2.0.111"
prettyplease = "0.2.37"
