name: Release Rust

on:
  workflow_dispatch:

jobs:

  release-rust:
    runs-on: ubuntu-latest

    env:
      PACKAGE_NAME: "agentic-pipelines-scheme"
      PACKAGE_VERSION: "0.0.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust

      - name: Generate crate
        run: |
          cargo run -- \
            -i ../../schemas \
            -o ../../packages \
            --package-name "${{ env.PACKAGE_NAME }}" \
            --package-version "${{ env.PACKAGE_VERSION }}" \
            -v
        working-directory: tools/rust-generator

      - name: Run tests
        run: |
          cargo test --lib tests
        working-directory: packages/rust