name: Release Rust

on:
  workflow_dispatch:

jobs:

  release-rust:
    runs-on: ubuntu-latest

    env:
      CRATES_IO_API_KEY: ${{ secrets.CRATES_IO_API_KEY }}
      PACKAGE_NAME: "agentic-pipelines-scheme-dev"
      PACKAGE_VERSION: "0.0.1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust

      - name: Generate Rust crate
        run: |
          cargo run -- \
            -i ../../schemas \
            -o ../../packages \
            --package-name "${{ env.PACKAGE_NAME }}" \
            --package-version "${{ env.PACKAGE_VERSION }}" \
            -v
        working-directory: tools/rust-generator

      - name: Run tests
        run: |
          cargo test --verbose --lib tests
        working-directory: packages/rust

      - name: Cargo login
        run: |
          echo "${{ env.CRATES_IO_API_KEY }}" | cargo login

      - name: Publish package
        run: |
          cargo publish
        working-directory: packages/rust